### ISSUE TITLE
Craft RC11 — Field not visible

### ISSUE THREAD

**Issue by davidhellmann** [mmikkel/CpFieldInspect-Craft#1] opened 2018-02-21 13:46 UTC
Looks like in the new RC11 something is broken. No more gear Icon visible.

**Comment by mmikkel** [comment] 2018-02-21 13:56
Thanks for reporting, @davidhellmann – I'll check it out ASAP.

**Comment by mmikkel** [comment] 2018-02-21 14:10
Hi @davidhellmann, I just tested CP Field Inspect on RC10, 10.1 and 11 – it works everywhere on my end.

1. Note that the cogwheels will only be visible for users with **admin** accounts.

2. If you're using an admin account, can confirm that the plugin is installed, active and the latest version (1.0.2) and still don't see any cogwheels, it'd be awesome if you could give me the following additional info:

– Are all cogwheels missing, or just in particular places? Entries, categories, global sets..?
– Do you have any other CP-sentric plugins installed (i.e. CP CSS/JS or the like)?
– Which browser are you using?
– If you pop open your browser's dev tools panel; are there any JavaScript errors?

**Comment by mmikkel** [comment] 2018-02-21 14:23
Huh, this is weird. I can confirm that I am actually able to reproduce the issue on a site upgraded to RC11. On a clean install, it works. Uninstalling and re-installing the plugin doesn't seem to help.

**Comment by mmikkel** [comment] 2018-02-21 15:02
This is a really weird issue where the admin check returns a false negative (i.e. `false` for a logged in user who has admin privileges) on a site upgraded to RC11, but not on a clean RC11 install.

I'm researching the issue and will report back when there's a fix.

**Comment by mmikkel** [comment] 2018-02-21 15:20
I'm 99.99% positive that the issue is w/ Craft 3 RC11, and not with CP Field Inspect, so I'm holding off for now.

**Comment by mmikkel** [comment] 2018-02-22 08:51
Confirmed bug in Craft CMS 3.0.0.-RC11 that will be fixed in RC11.1 (tentative release date February 23d 2018) – closing this issue.

**Closed as completed** 2018-02-22 08:51 UTC

**Comment by davidhellmann** [comment] 2018-02-23 20:34
OK wired. Sorry for stress, hehe. But yes, looks fine. ¯\_(ツ)_/¯

**Comment by mmikkel** [comment] 2018-02-23 20:35
@davidhellmann Absolutely no stress whatsover :) Thanks for contributing!
