### ISSUE TITLE
It doesn't seem to show the gear button anymore on Craft 3.0.25

### ISSUE THREAD

**Issue by pierreluckffein** [mmikkel/CpFieldInspect-Craft#7] opened 2018-10-05 14:25 UTC
The gear doesn't seem to appear with this Craftcms fix
[0282fe5](https://github.com/craftcms/cms/commit/0282fe5c3a390194a495a0dfef1a0e50b7cc8505#diff-d425917d44ba312029cbb04807d3472f)
Basically the plugin is now loaded in postInit and the functions Craft::$app->getFields() returns an empty array now.

**Comment by mmikkel** [comment] 2018-10-05 17:17
Hi @pierreluckffein, thanks for contributing. 

I just tested CP Field Inspect on fresh installs of Craft 3.0.25 and 3.0.26.1, and the cogwheels are displaying for me.

[`0282fe5`](https://github.com/craftcms/cms/commit/0282fe5c3a390194a495a0dfef1a0e50b7cc8505#diff-d425917d44ba312029cbb04807d3472f) being the cause for this issue sounds a bit odd to me. Do you mind typing out some details on how you reached this conclusion?

This issue (i.e. cogwheels not appearing) has been reported before, and it has typically turned out to be a different plugin interacting with some of Craft's bootup events in such a way that CP Field Inspect's asset bundle never gets initialised (i.e. the JS and CSS neccessary to display the cogwheels doesn't load).

Assuming that's the case here as well, here's a few things to try:

– Disable (not uninstall! and be sure to back up your database) all other plugins. Do it one by one, check if the cogwheels appear after deactivating each one.
– Check your browser's dev tools console for any JS errors
– Check your browser's dev tools' network tab to see if the files `cpfieldinspect.js` and `cpfieldinspect.css` are in fact requested, or if they're missing
– Clear your Control Panel Resources 
– Make sure you're on the latest version of CP Field Inspect (3.0.5)

If it does turn out to be another plugin colliding w/ CP Field Inspect, I'd love to know which one, so we can patch the issue (either on my end or theirs).

**Comment by pierreluckffein** [comment] 2018-10-05 19:28
Yeah, sorry. I found my problem, I thought it was because of an update because when I changed back in ApplicationTrait.php loadplugin() in _preInit() it made the gear reappear, but there was a module installed that might have to do with the error and with the order in which module and plugin are loaded it made the gear dissappear but it seems to be an error on my behalf inside the module.

But, thanks for answering me , it narrowed the problem for me, would have taken much more hours of work to find the solution without you.

**Comment by pierreluckffein** [comment] 2018-10-05 20:05
apparently i found that this line might be the problem : 
`Craft::$app->getUser()->getIsAdmin();`

When I try to check if the user is admin it made the gear disappear and it has something to do with the fix that I mentioned earlier.

**Comment by mmikkel** [comment] 2018-10-05 21:58
Thanks for the follow-up, @pierreluckffein! I'm going to put this down as an issue either with the custom module you mention, or with Craft itself (if it turns out to be the latter, you should open an issue in the [Craft CMS](https://github.com/craftcms/cms) repo). If it turns out to be something that you think Field Inspect could and should circumvent, please let me know. Closing for now :)

**Closed as completed by mmikkel** 2018-10-05 21:58 UTC
Labels: unable to reproduce
